/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConverterRouteImport } from './routes/converter'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSqliteRouteImport } from './routes/docs/sqlite'
import { Route as DocsMysqlRouteImport } from './routes/docs/mysql'
import { Route as DocsMssqlRouteImport } from './routes/docs/mssql'
import { Route as DocsPgValidationRouteImport } from './routes/docs/pg/validation'
import { Route as DocsPgUpdateDeleteRouteImport } from './routes/docs/pg/update-delete'
import { Route as DocsPgTransactionsRouteImport } from './routes/docs/pg/transactions'
import { Route as DocsPgSqlSchemaRouteImport } from './routes/docs/pg/sql-schema'
import { Route as DocsPgSelectRouteImport } from './routes/docs/pg/select'
import { Route as DocsPgRawRouteImport } from './routes/docs/pg/raw'
import { Route as DocsPgQueryBuilderRouteImport } from './routes/docs/pg/query-builder'
import { Route as DocsPgPredicatesRouteImport } from './routes/docs/pg/predicates'
import { Route as DocsPgOrderingRouteImport } from './routes/docs/pg/ordering'
import { Route as DocsPgOperatorsRouteImport } from './routes/docs/pg/operators'
import { Route as DocsPgJoinsRouteImport } from './routes/docs/pg/joins'
import { Route as DocsPgInsertRouteImport } from './routes/docs/pg/insert'
import { Route as DocsPgHelpersRouteImport } from './routes/docs/pg/helpers'
import { Route as DocsPgFunctionCallRouteImport } from './routes/docs/pg/function-call'
import { Route as DocsPgDbSchemaRouteImport } from './routes/docs/pg/db-schema'
import { Route as DocsPgCliRouteImport } from './routes/docs/pg/cli'
import { Route as DocsPgInstallationIndexRouteImport } from './routes/docs/pg/installation/index'

const ConverterRoute = ConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSqliteRoute = DocsSqliteRouteImport.update({
  id: '/sqlite',
  path: '/sqlite',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMysqlRoute = DocsMysqlRouteImport.update({
  id: '/mysql',
  path: '/mysql',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsMssqlRoute = DocsMssqlRouteImport.update({
  id: '/mssql',
  path: '/mssql',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgValidationRoute = DocsPgValidationRouteImport.update({
  id: '/pg/validation',
  path: '/pg/validation',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgUpdateDeleteRoute = DocsPgUpdateDeleteRouteImport.update({
  id: '/pg/update-delete',
  path: '/pg/update-delete',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgTransactionsRoute = DocsPgTransactionsRouteImport.update({
  id: '/pg/transactions',
  path: '/pg/transactions',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgSqlSchemaRoute = DocsPgSqlSchemaRouteImport.update({
  id: '/pg/sql-schema',
  path: '/pg/sql-schema',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgSelectRoute = DocsPgSelectRouteImport.update({
  id: '/pg/select',
  path: '/pg/select',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgRawRoute = DocsPgRawRouteImport.update({
  id: '/pg/raw',
  path: '/pg/raw',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgQueryBuilderRoute = DocsPgQueryBuilderRouteImport.update({
  id: '/pg/query-builder',
  path: '/pg/query-builder',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgPredicatesRoute = DocsPgPredicatesRouteImport.update({
  id: '/pg/predicates',
  path: '/pg/predicates',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgOrderingRoute = DocsPgOrderingRouteImport.update({
  id: '/pg/ordering',
  path: '/pg/ordering',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgOperatorsRoute = DocsPgOperatorsRouteImport.update({
  id: '/pg/operators',
  path: '/pg/operators',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgJoinsRoute = DocsPgJoinsRouteImport.update({
  id: '/pg/joins',
  path: '/pg/joins',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgInsertRoute = DocsPgInsertRouteImport.update({
  id: '/pg/insert',
  path: '/pg/insert',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgHelpersRoute = DocsPgHelpersRouteImport.update({
  id: '/pg/helpers',
  path: '/pg/helpers',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgFunctionCallRoute = DocsPgFunctionCallRouteImport.update({
  id: '/pg/function-call',
  path: '/pg/function-call',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgDbSchemaRoute = DocsPgDbSchemaRouteImport.update({
  id: '/pg/db-schema',
  path: '/pg/db-schema',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgCliRoute = DocsPgCliRouteImport.update({
  id: '/pg/cli',
  path: '/pg/cli',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsPgInstallationIndexRoute = DocsPgInstallationIndexRouteImport.update({
  id: '/pg/installation/',
  path: '/pg/installation/',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/converter': typeof ConverterRoute
  '/docs/mssql': typeof DocsMssqlRoute
  '/docs/mysql': typeof DocsMysqlRoute
  '/docs/sqlite': typeof DocsSqliteRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/pg/cli': typeof DocsPgCliRoute
  '/docs/pg/db-schema': typeof DocsPgDbSchemaRoute
  '/docs/pg/function-call': typeof DocsPgFunctionCallRoute
  '/docs/pg/helpers': typeof DocsPgHelpersRoute
  '/docs/pg/insert': typeof DocsPgInsertRoute
  '/docs/pg/joins': typeof DocsPgJoinsRoute
  '/docs/pg/operators': typeof DocsPgOperatorsRoute
  '/docs/pg/ordering': typeof DocsPgOrderingRoute
  '/docs/pg/predicates': typeof DocsPgPredicatesRoute
  '/docs/pg/query-builder': typeof DocsPgQueryBuilderRoute
  '/docs/pg/raw': typeof DocsPgRawRoute
  '/docs/pg/select': typeof DocsPgSelectRoute
  '/docs/pg/sql-schema': typeof DocsPgSqlSchemaRoute
  '/docs/pg/transactions': typeof DocsPgTransactionsRoute
  '/docs/pg/update-delete': typeof DocsPgUpdateDeleteRoute
  '/docs/pg/validation': typeof DocsPgValidationRoute
  '/docs/pg/installation/': typeof DocsPgInstallationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/converter': typeof ConverterRoute
  '/docs/mssql': typeof DocsMssqlRoute
  '/docs/mysql': typeof DocsMysqlRoute
  '/docs/sqlite': typeof DocsSqliteRoute
  '/docs': typeof DocsIndexRoute
  '/docs/pg/cli': typeof DocsPgCliRoute
  '/docs/pg/db-schema': typeof DocsPgDbSchemaRoute
  '/docs/pg/function-call': typeof DocsPgFunctionCallRoute
  '/docs/pg/helpers': typeof DocsPgHelpersRoute
  '/docs/pg/insert': typeof DocsPgInsertRoute
  '/docs/pg/joins': typeof DocsPgJoinsRoute
  '/docs/pg/operators': typeof DocsPgOperatorsRoute
  '/docs/pg/ordering': typeof DocsPgOrderingRoute
  '/docs/pg/predicates': typeof DocsPgPredicatesRoute
  '/docs/pg/query-builder': typeof DocsPgQueryBuilderRoute
  '/docs/pg/raw': typeof DocsPgRawRoute
  '/docs/pg/select': typeof DocsPgSelectRoute
  '/docs/pg/sql-schema': typeof DocsPgSqlSchemaRoute
  '/docs/pg/transactions': typeof DocsPgTransactionsRoute
  '/docs/pg/update-delete': typeof DocsPgUpdateDeleteRoute
  '/docs/pg/validation': typeof DocsPgValidationRoute
  '/docs/pg/installation': typeof DocsPgInstallationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/converter': typeof ConverterRoute
  '/docs/mssql': typeof DocsMssqlRoute
  '/docs/mysql': typeof DocsMysqlRoute
  '/docs/sqlite': typeof DocsSqliteRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/pg/cli': typeof DocsPgCliRoute
  '/docs/pg/db-schema': typeof DocsPgDbSchemaRoute
  '/docs/pg/function-call': typeof DocsPgFunctionCallRoute
  '/docs/pg/helpers': typeof DocsPgHelpersRoute
  '/docs/pg/insert': typeof DocsPgInsertRoute
  '/docs/pg/joins': typeof DocsPgJoinsRoute
  '/docs/pg/operators': typeof DocsPgOperatorsRoute
  '/docs/pg/ordering': typeof DocsPgOrderingRoute
  '/docs/pg/predicates': typeof DocsPgPredicatesRoute
  '/docs/pg/query-builder': typeof DocsPgQueryBuilderRoute
  '/docs/pg/raw': typeof DocsPgRawRoute
  '/docs/pg/select': typeof DocsPgSelectRoute
  '/docs/pg/sql-schema': typeof DocsPgSqlSchemaRoute
  '/docs/pg/transactions': typeof DocsPgTransactionsRoute
  '/docs/pg/update-delete': typeof DocsPgUpdateDeleteRoute
  '/docs/pg/validation': typeof DocsPgValidationRoute
  '/docs/pg/installation/': typeof DocsPgInstallationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/converter'
    | '/docs/mssql'
    | '/docs/mysql'
    | '/docs/sqlite'
    | '/docs/'
    | '/docs/pg/cli'
    | '/docs/pg/db-schema'
    | '/docs/pg/function-call'
    | '/docs/pg/helpers'
    | '/docs/pg/insert'
    | '/docs/pg/joins'
    | '/docs/pg/operators'
    | '/docs/pg/ordering'
    | '/docs/pg/predicates'
    | '/docs/pg/query-builder'
    | '/docs/pg/raw'
    | '/docs/pg/select'
    | '/docs/pg/sql-schema'
    | '/docs/pg/transactions'
    | '/docs/pg/update-delete'
    | '/docs/pg/validation'
    | '/docs/pg/installation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/converter'
    | '/docs/mssql'
    | '/docs/mysql'
    | '/docs/sqlite'
    | '/docs'
    | '/docs/pg/cli'
    | '/docs/pg/db-schema'
    | '/docs/pg/function-call'
    | '/docs/pg/helpers'
    | '/docs/pg/insert'
    | '/docs/pg/joins'
    | '/docs/pg/operators'
    | '/docs/pg/ordering'
    | '/docs/pg/predicates'
    | '/docs/pg/query-builder'
    | '/docs/pg/raw'
    | '/docs/pg/select'
    | '/docs/pg/sql-schema'
    | '/docs/pg/transactions'
    | '/docs/pg/update-delete'
    | '/docs/pg/validation'
    | '/docs/pg/installation'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/converter'
    | '/docs/mssql'
    | '/docs/mysql'
    | '/docs/sqlite'
    | '/docs/'
    | '/docs/pg/cli'
    | '/docs/pg/db-schema'
    | '/docs/pg/function-call'
    | '/docs/pg/helpers'
    | '/docs/pg/insert'
    | '/docs/pg/joins'
    | '/docs/pg/operators'
    | '/docs/pg/ordering'
    | '/docs/pg/predicates'
    | '/docs/pg/query-builder'
    | '/docs/pg/raw'
    | '/docs/pg/select'
    | '/docs/pg/sql-schema'
    | '/docs/pg/transactions'
    | '/docs/pg/update-delete'
    | '/docs/pg/validation'
    | '/docs/pg/installation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  ConverterRoute: typeof ConverterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/converter': {
      id: '/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/sqlite': {
      id: '/docs/sqlite'
      path: '/sqlite'
      fullPath: '/docs/sqlite'
      preLoaderRoute: typeof DocsSqliteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/mysql': {
      id: '/docs/mysql'
      path: '/mysql'
      fullPath: '/docs/mysql'
      preLoaderRoute: typeof DocsMysqlRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/mssql': {
      id: '/docs/mssql'
      path: '/mssql'
      fullPath: '/docs/mssql'
      preLoaderRoute: typeof DocsMssqlRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/validation': {
      id: '/docs/pg/validation'
      path: '/pg/validation'
      fullPath: '/docs/pg/validation'
      preLoaderRoute: typeof DocsPgValidationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/update-delete': {
      id: '/docs/pg/update-delete'
      path: '/pg/update-delete'
      fullPath: '/docs/pg/update-delete'
      preLoaderRoute: typeof DocsPgUpdateDeleteRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/transactions': {
      id: '/docs/pg/transactions'
      path: '/pg/transactions'
      fullPath: '/docs/pg/transactions'
      preLoaderRoute: typeof DocsPgTransactionsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/sql-schema': {
      id: '/docs/pg/sql-schema'
      path: '/pg/sql-schema'
      fullPath: '/docs/pg/sql-schema'
      preLoaderRoute: typeof DocsPgSqlSchemaRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/select': {
      id: '/docs/pg/select'
      path: '/pg/select'
      fullPath: '/docs/pg/select'
      preLoaderRoute: typeof DocsPgSelectRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/raw': {
      id: '/docs/pg/raw'
      path: '/pg/raw'
      fullPath: '/docs/pg/raw'
      preLoaderRoute: typeof DocsPgRawRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/query-builder': {
      id: '/docs/pg/query-builder'
      path: '/pg/query-builder'
      fullPath: '/docs/pg/query-builder'
      preLoaderRoute: typeof DocsPgQueryBuilderRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/predicates': {
      id: '/docs/pg/predicates'
      path: '/pg/predicates'
      fullPath: '/docs/pg/predicates'
      preLoaderRoute: typeof DocsPgPredicatesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/ordering': {
      id: '/docs/pg/ordering'
      path: '/pg/ordering'
      fullPath: '/docs/pg/ordering'
      preLoaderRoute: typeof DocsPgOrderingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/operators': {
      id: '/docs/pg/operators'
      path: '/pg/operators'
      fullPath: '/docs/pg/operators'
      preLoaderRoute: typeof DocsPgOperatorsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/joins': {
      id: '/docs/pg/joins'
      path: '/pg/joins'
      fullPath: '/docs/pg/joins'
      preLoaderRoute: typeof DocsPgJoinsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/insert': {
      id: '/docs/pg/insert'
      path: '/pg/insert'
      fullPath: '/docs/pg/insert'
      preLoaderRoute: typeof DocsPgInsertRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/helpers': {
      id: '/docs/pg/helpers'
      path: '/pg/helpers'
      fullPath: '/docs/pg/helpers'
      preLoaderRoute: typeof DocsPgHelpersRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/function-call': {
      id: '/docs/pg/function-call'
      path: '/pg/function-call'
      fullPath: '/docs/pg/function-call'
      preLoaderRoute: typeof DocsPgFunctionCallRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/db-schema': {
      id: '/docs/pg/db-schema'
      path: '/pg/db-schema'
      fullPath: '/docs/pg/db-schema'
      preLoaderRoute: typeof DocsPgDbSchemaRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/cli': {
      id: '/docs/pg/cli'
      path: '/pg/cli'
      fullPath: '/docs/pg/cli'
      preLoaderRoute: typeof DocsPgCliRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/pg/installation/': {
      id: '/docs/pg/installation/'
      path: '/pg/installation'
      fullPath: '/docs/pg/installation/'
      preLoaderRoute: typeof DocsPgInstallationIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsMssqlRoute: typeof DocsMssqlRoute
  DocsMysqlRoute: typeof DocsMysqlRoute
  DocsSqliteRoute: typeof DocsSqliteRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsPgCliRoute: typeof DocsPgCliRoute
  DocsPgDbSchemaRoute: typeof DocsPgDbSchemaRoute
  DocsPgFunctionCallRoute: typeof DocsPgFunctionCallRoute
  DocsPgHelpersRoute: typeof DocsPgHelpersRoute
  DocsPgInsertRoute: typeof DocsPgInsertRoute
  DocsPgJoinsRoute: typeof DocsPgJoinsRoute
  DocsPgOperatorsRoute: typeof DocsPgOperatorsRoute
  DocsPgOrderingRoute: typeof DocsPgOrderingRoute
  DocsPgPredicatesRoute: typeof DocsPgPredicatesRoute
  DocsPgQueryBuilderRoute: typeof DocsPgQueryBuilderRoute
  DocsPgRawRoute: typeof DocsPgRawRoute
  DocsPgSelectRoute: typeof DocsPgSelectRoute
  DocsPgSqlSchemaRoute: typeof DocsPgSqlSchemaRoute
  DocsPgTransactionsRoute: typeof DocsPgTransactionsRoute
  DocsPgUpdateDeleteRoute: typeof DocsPgUpdateDeleteRoute
  DocsPgValidationRoute: typeof DocsPgValidationRoute
  DocsPgInstallationIndexRoute: typeof DocsPgInstallationIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsMssqlRoute: DocsMssqlRoute,
  DocsMysqlRoute: DocsMysqlRoute,
  DocsSqliteRoute: DocsSqliteRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsPgCliRoute: DocsPgCliRoute,
  DocsPgDbSchemaRoute: DocsPgDbSchemaRoute,
  DocsPgFunctionCallRoute: DocsPgFunctionCallRoute,
  DocsPgHelpersRoute: DocsPgHelpersRoute,
  DocsPgInsertRoute: DocsPgInsertRoute,
  DocsPgJoinsRoute: DocsPgJoinsRoute,
  DocsPgOperatorsRoute: DocsPgOperatorsRoute,
  DocsPgOrderingRoute: DocsPgOrderingRoute,
  DocsPgPredicatesRoute: DocsPgPredicatesRoute,
  DocsPgQueryBuilderRoute: DocsPgQueryBuilderRoute,
  DocsPgRawRoute: DocsPgRawRoute,
  DocsPgSelectRoute: DocsPgSelectRoute,
  DocsPgSqlSchemaRoute: DocsPgSqlSchemaRoute,
  DocsPgTransactionsRoute: DocsPgTransactionsRoute,
  DocsPgUpdateDeleteRoute: DocsPgUpdateDeleteRoute,
  DocsPgValidationRoute: DocsPgValidationRoute,
  DocsPgInstallationIndexRoute: DocsPgInstallationIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  ConverterRoute: ConverterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
